# Koyeb部署配置文件
apiVersion: koyeb.com/v1
kind: App
metadata:
  name: lark-email-sync
spec:
  services:
    - name: web
      type: web
      ports:
        - port: 8000
          protocol: http
      build:
        type: docker
        dockerfile: Dockerfile
      instance:
        type: nano
      scaling:
        min: 1
        max: 1
      env:
        # 基础环境变量
        - name: FLASK_ENV
          value: production
        - name: PYTHONUNBUFFERED
          value: "1"
        # 注意：所有业务配置现在通过HTTP请求参数传递，无需环境变量
      healthcheck:
        http:
          path: /health
          port: 8000
        initial_delay: 30
        timeout: 10
        interval: 30
        retries: 3
      regions:
        - fra  # 法兰克福区域，可根据需要调整
      # 资源限制
      resources:
        memory: 512Mi
        cpu: 0.1
      # 自动重启策略
      restart_policy: always