# Koyeb部署配置文件
apiVersion: koyeb.com/v1
kind: App
metadata:
  name: lark-email-sync
spec:
  services:
    - name: web
      type: web
      ports:
        - port: 8000
          protocol: http
      build:
        type: docker
        dockerfile: Dockerfile
      instance:
        type: nano
      scaling:
        min: 1
        max: 1
      env:
        # 环境变量将通过Koyeb控制台或CLI设置
        - name: FLASK_ENV
          value: production
        - name: PYTHONUNBUFFERED
          value: "1"
        # 飞书相关环境变量
        - name: BITABLE_URL
          from_secret: BITABLE_URL
        - name: PERSONAL_BASE_TOKEN
          from_secret: PERSONAL_BASE_TOKEN
        # 邮件相关环境变量
        - name: EMAIL_USERNAME
          from_secret: EMAIL_USERNAME
        - name: EMAIL_PASSWORD
          from_secret: EMAIL_PASSWORD
        - name: EMAIL_PROVIDER
          from_secret: EMAIL_PROVIDER
        - name: EMAIL_COUNT
          from_secret: EMAIL_COUNT
      healthcheck:
        http:
          path: /health
          port: 8000
        initial_delay: 30
        timeout: 10
        interval: 30
        retries: 3
      regions:
        - fra  # 法兰克福区域，可根据需要调整
      # 资源限制
      resources:
        memory: 512Mi
        cpu: 0.1
      # 自动重启策略
      restart_policy: always