services:
  - type: web
    name: lark-email-sync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    disk:
      name: lark-email-sync-disk
      mountPath: /opt/render/project/src
      sizeGB: 1