name: Email to Feishu Bitable Sync

on:
  workflow_dispatch:
    inputs:
      bitable_url:
        description: '飞书多维表格URL'
        required: true
        type: string
      app_token:
        description: '飞书应用Token'
        required: true
        type: string
      personal_base_token:
        description: '飞书个人基础Token'
        required: true
        type: string
      email_username:
        description: '邮箱用户名'
        required: true
        type: string
      email_password:
        description: '邮箱授权码'
        required: true
        type: string
      email_provider:
        description: '邮箱服务商'
        required: true
        default: 'feishu'
        type: choice
        options:
          - feishu
          - gmail
          - outlook
          - qq
          - 163
          - 126
      email_count:
        description: '获取邮件数量'
        required: false
        default: '10'
        type: string
  repository_dispatch:
    types: [email-sync]

jobs:
  sync-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run email sync
      env:
        BITABLE_URL: ${{ github.event.inputs.bitable_url || github.event.client_payload.bitable_url }}
        APP_TOKEN: ${{ github.event.inputs.app_token || github.event.client_payload.app_token }}
        PERSONAL_BASE_TOKEN: ${{ github.event.inputs.personal_base_token || github.event.client_payload.personal_base_token }}
        EMAIL_USERNAME: ${{ github.event.inputs.email_username || github.event.client_payload.email_username }}
        EMAIL_PASSWORD: ${{ github.event.inputs.email_password || github.event.client_payload.email_password }}
        EMAIL_PROVIDER: ${{ github.event.inputs.email_provider || github.event.client_payload.email_provider || 'feishu' }}
        EMAIL_COUNT: ${{ github.event.inputs.email_count || github.event.client_payload.email_count || '10' }}
      run: |
        python email_sync_action.py
    
    - name: Upload sync results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: sync-results
        path: |
          sync_result.json
          sync_logs.json
        retention-days: 7